-- Table: camdecmpsaux.check_rule

-- DROP TABLE camdecmpsaux.check_rule;

CREATE TABLE camdecmpsaux.check_rule
(
    check_rule_id uuid NOT NULL,
    check_rule_cd character varying NOT NULL,
    check_rule_name character varying NOT NULL,
    check_rule_description character varying NOT NULL,
    check_rule_type_cd character varying NOT NULL,
    check_rule_category_cd character varying NOT NULL,
    check_rule_priority NUMERIC NOT NULL,
    check_rule_xml character varying,
    check_rule_json character varying,
    is_error_supressable boolean,
    is_active boolean,
--    userid character varying(8) COLLATE pg_catalog."default",
--    add_date date,
--    update_date date,
    CONSTRAINT pk_check_rule PRIMARY KEY (check_rule_id),
    CONSTRAINT uq_check_rule_code UNIQUE (check_rule_cd),
    CONSTRAINT fk_check_rule_type FOREIGN KEY (check_rule_type_cd)
        REFERENCES camdecmpsaux.check_rule_type (check_rule_type_cd) MATCH SIMPLE,
    CONSTRAINT fk_check_rule_category FOREIGN KEY (check_rule_category_cd)
        REFERENCES camdecmpsaux.check_category (check_category_cd) MATCH SIMPLE
);

COMMENT ON TABLE camdecmpsaux.check_rule
    IS 'Rules used by the check engine business rule evaluation processes.';

COMMENT ON COLUMN camdecmpsaux.check_rule.check_rule_id
    IS 'Id used to identify check rule generated by Code Effects Rule Editor.';

COMMENT ON COLUMN camdecmpsaux.check_rule.check_rule_cd
    IS 'Code used to identify check rule.';

COMMENT ON COLUMN camdecmpsaux.check_rule.check_rule_name
    IS 'Name used to identify check rule.';

COMMENT ON COLUMN camdecmpsaux.check_rule.check_rule_description
    IS 'Description of check rule.';

COMMENT ON COLUMN camdecmpsaux.check_rule.check_rule_type_cd
    IS 'The check rule type the check rule is associated with.';

COMMENT ON COLUMN camdecmpsaux.check_rule.check_rule_category_cd
    IS 'The check rule category the check rule is associated with.';

COMMENT ON COLUMN camdecmpsaux.check_rule.check_rule_priority
    IS 'The priority order in which check rules are evaluated within a check rule category.';

COMMENT ON COLUMN camdecmpsaux.check_rule.check_rule_xml
    IS 'The check rule xml generated by the Code Effects Business Rule Engine and used by the evaluation processes.';

COMMENT ON COLUMN camdecmpsaux.check_rule.check_rule_json
    IS 'The check rule json generated by the Code Effects Business Rule Engine and used by the rule editor.';

COMMENT ON COLUMN camdecmpsaux.check_rule.is_error_supressable
    IS 'Indicates whether errors resulting from the evaluation process can be suppresed for submisson.';

COMMENT ON COLUMN camdecmpsaux.check_rule.is_active
    IS 'Indicates whether the rule is active and used by the evaluation process.';

-- COMMENT ON COLUMN camdecmpsaux.check_rule.userid
--     IS 'User account or source of data that added or updated record. ';

-- COMMENT ON COLUMN camdecmpsaux.check_rule.add_date
--     IS 'Date and time in which record was added. ';

-- COMMENT ON COLUMN camdecmpsaux.check_rule.update_date
--     IS 'Date and time in which record was last updated. ';

-- Index: idx_check_rule_type

-- DROP INDEX camdecmpsaux.idx_check_rule_type;

CREATE INDEX idx_check_rule_type
    ON camdecmpsaux.check_rule USING btree
    (check_rule_type_cd ASC NULLS LAST);

-- Index: idx_check_rule_category

-- DROP INDEX camdecmpsaux.idx_check_rule_category;

CREATE INDEX idx_check_rule_category
    ON camdecmpsaux.check_rule USING btree
    (check_rule_category_cd ASC NULLS LAST);
