cf set-env $APP_NAME AWS_ACCESS_KEY_ID $S3_AWS_ACCESS_KEY_ID
cf set-env $APP_NAME AWS_SECRET_ACCESS_KEY $S3_AWS_SECRET_ACCESS_KEY
cf set-env $APP_NAME EASEY_CAMD_SERVICES_API_KEY $CAMD_SVCS_NON_PROD_API_KEY 
cf set-env $APP_NAME EASEY_CAMD_SERVICES_SECRET_TOKEN $CAMD_SERVICES_API_SECRET_TOKEN
