name: "API Full ZAP Scan"
on:
    workflow_dispatch:
        inputs:
            openapiurl:
                description: 'The OpenAPI swagger json to import'
                required: true
                default: 'https://api.epa.gov/easey/dev/master-data-mgmt/swagger-json'
            openapitargeturl:
                description: 'The OpenAPI target url to scan'
                required: true
                default: 'https://api.epa.gov/easey/dev/master-data-mgmt/'
            zapscanpolicy:
                description: 'The ZAP scan policy to use'
                required: true
                type: choice
                options: 
                    - 'Default Policy' 
                    - 'St-High-Th-Low'
                    - 'St-High-Th-Medium'
                    - 'St-High-Th-High'
                    - 'St-Medium-Th-Low'
                    - 'St-Medium-Th-Medium'
                    - 'St-Medium-Th-High'
                    - 'St-Low-Th-Low'
                    - 'St-Low-Th-Medium'
                    - 'St-Low-Th-High'
env:
    ZAP_SCAN_POLICY: ${{ github.event.inputs.zapscanpolicy }}
jobs:
    zap_scan:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Run ZAP Scan
          uses: zaproxy/action-full-scan@v0.11.0
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            target: ${{ github.event.inputs.openapitargeturl }}
            docker_name: 'ghcr.io/zaproxy/zaproxy:latest'
            allow_issue_writing: 'false'
            rules_file_name: 'rules-api.tsv'
            cmd_options: "-a -d --hook=scan-hooks/api_scan.py -z \"-addoninstall openapi -openapiurl ${{ github.event.inputs.openapiurl }} -openapitargeturl ${{ github.event.inputs.openapitargeturl }} -config replacer.full_list\\(0\\).description=auth1 -config replacer.full_list\\(0\\).enabled=true -config replacer.full_list\\(0\\).matchtype=REQ_HEADER -config replacer.full_list\\(0\\).matchstr=x-api-key -config replacer.full_list\\(0\\).regex=false -config replacer.full_list\\(0\\).replacement=${{ secrets.OWASP_ZAP_SCAN_API_KEY }}\""
