name: "API Full ZAP Scan"
on:
    workflow_dispatch:
        inputs:
            openapiurl:
                description: 'The OpenAPI URL to scan'
                required: true
                default: 'https://api.epa.gov/easey/dev/master-data-mgmt/swagger-json'
jobs:
    zap_scan:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Run ZAP Scan
          uses: zaproxy/action-full-scan@v0.11.0
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            target: ${{ github.event.inputs.openapiurl }}
            docker_name: 'ghcr.io/zaproxy/zaproxy:latest'
            allow_issue_writing: 'false'
            rules_file_name: 'rules-api.tsv'
            cmd_options: "-a -d -z \"-config replacer.full_list\\(0\\).description=auth1 -config replacer.full_list\\(0\\).enabled=true -config replacer.full_list\\(0\\).matchtype=REQ_HEADER -config replacer.full_list\\(0\\).matchstr=x-api-key -config replacer.full_list\\(0\\).regex=false -config replacer.full_list\\(0\\).replacement=${{ secrets.OWASP_ZAP_SCAN_API_KEY }}\""
