name: "Facilities Mgmt API ZAP Scan"
on: workflow_dispatch
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan Facilities Mgmt API
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Configure Env Vars
        run: scripts/environment-variables.sh          
      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          format: openapi
          issue_title: 'Facilities Mgmt API ZAP Scan'
          target: 'https://api-easey-dev.app.cloud.gov/facilities-mgmt/swagger-json'
          rules_file_name: 'rules.tsv'
          cmd_options: '-a'
      - name: Package reports
        run: scripts/zap-api-scan.sh easey-facilities-api
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ARTIFACTS_STORAGE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ARTIFACTS_STORAGE_SECRET_ACCESS_KEY }}

          
