name: "QA Certification Data Mgmt API ZAP Scan"
on: 
  schedule:
    - cron: '30 6 * * 6'
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan QA Certification Mgmt API
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Configure Env Vars
        run: scripts/environment-variables.sh          
      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          issue_title: 'QA Certification Mgmt API ZAP Scan'
          target: 'https://api-easey-dev.app.cloud.gov/qa-certification-mgmt/swagger-json'
          cmd_options: '-a -c rules.tsv'
      - name: Package reports
        run: scripts/zap-api-scan.sh easey-qa-certification-api
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ARTIFACTS_STORAGE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ARTIFACTS_STORAGE_SECRET_ACCESS_KEY }}
