name: Build Package Workflow

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true
      SONAR_TOKEN:
        required: true
      ARTIFACTS_STORAGE_ACCESS_KEY_ID:
        required: true        
      ARTIFACTS_STORAGE_SECRET_ACCESS_KEY:
        required: true

jobs:
  Build-Package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Checkout devops repo
        uses: actions/checkout@v2
        with:
          repository: US-EPA-CAMD/devops
          path: devops
      - name: Setup & Configure Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@us-epa-camd'
      - name: Configure Env Vars
        run: devops/scripts/environment-variables-noTag.sh
        env:
          ENV_VAR_PREFIX: EASEY
      - name: Build
        run: devops/scripts/yarn/build.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Unit Tests
        run: devops/scripts/yarn/unit-tests.sh
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Package App
        run: devops/scripts/package-artifact.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ARTIFACTS_STORAGE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ARTIFACTS_STORAGE_SECRET_ACCESS_KEY }}