name: Deploy Package Workflow

on:
  workflow_call:
    inputs:
      ENV:
        description: 'Environmnet to Deploy to (should be from dropdown)'
        required: true
        type: string
      PACKAGE:
        description: 'Package name to deploy, set to latest (default) to fetch latest package'
        required: false
        default: 'latest'
        type: string
jobs:
  Deployment:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.ENV }}
      url: https://api.epa.gov/easey/${{ inputs.ENV.lowercase }}/camd-services/swagger
    env:
      URL: 'https://api.epa.gov/easey/'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Checkout devops repo
        uses: actions/checkout@v2
        with:
          repository: US-EPA-CAMD/devops
          path: devops
      - name: Configure Env Vars
        run: devops/scripts/environment-variables-deploy.sh
        env:
          ENV_VAR_PREFIX: EASEY
          PACKAGE: ${{ inputs.PACKAGE }}
          ENV: ${{ inputs.ENV }}
          AWS_ACCESS_KEY_ID: ${{ secrets.ARTIFACTS_STORAGE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ARTIFACTS_STORAGE_SECRET_ACCESS_KEY }}
      - name: Install cf cli
        run: devops/scripts/install-cf-cli.sh
      - name: Login to cloud.gov
        run: devops/scripts/cf-login.sh
        env:
          CF_USERNAME: ${{ env.CF_ENV_DEPLOYMENT_SVC }}
          CF_PASSWORD: ${{ env.CF_ENV_DEPLOYMENT_SVC_PWD }}
      - name: Download Deployment Package
        run: devops/scripts/download-artifact.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ARTIFACTS_STORAGE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ARTIFACTS_STORAGE_SECRET_ACCESS_KEY }}
